version: 2
jobs:
  test:
     docker:
       - image: circleci/clojure:lein
     steps:
       - checkout
       - run:
           command: lein run -m re-crud.mock-http-server
           background: true
       - run: for i in `seq 120`; do nc -v -w 1 localhost 8000 && break ; sleep 1; done
       - run: make test
